<?xml version="1.0"?>
<package format="3">
  <name>lexium_cobot_pick_and_place</name>
  <version>0.1.0</version>
  <description>Assignment 02 ROS2 demo for Lexium Cobot pick-and-place workcell.</description>
  <maintainer email="adilkhan@example.com">Adilkhan Kaldybekov</maintainer>
  <license>MIT</license>

  <depend>rclpy</depend>
  <depend>std_msgs</depend>

  <export>
    <build_type>ament_python</build_type>
  </export>
</package>
